# -*- coding: utf-8 -*-
"""Copy of salary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blhsqR5fMrY6XbF3om8-WrnV6OfJE_gI
"""

# prompt: import pandas

import pandas as pd

import numpy as np

salary = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/refs/heads/main/Salary%20Data.csv')

salary.head()

salary.info()

salary.describe()

salary.columns

salary.shape

y = salary['Salary']

x =salary [[ 'Experience Years' ]]

salary.shape

x.shape

y.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train ,y_test=train_test_split(x,y,random_state= 2529)
x_train

x_train.shape,x_test.shape,y_train.shape ,y_test.shape

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(x_train, y_train)

model.intercept_

model.coef_

y_pred= model.predict(x_test)

x_test

from sklearn.metrics import mean_absolute_percentage_error

mean_absolute_percentage_error(y_test,y_pred)